[theme]
base="light"
primaryColor="#2563eb"       # синий (корпоративный)
backgroundColor="#ffffff"
secondaryBackgroundColor="#f6f7fb"
textColor="#111827"
font="sans serif"

[server]
headless=true

[browser]
gatherUsageStats=false